id = "cfml"
name = "CFML"
description = "CFML support."
version = "0.1.0"
schema_version = 1
authors = ["Gareth Edwards <ghedwards@gmail.com>"]
repository = "https://github.com/cfmleditor/zed-cfml"

[grammars.cfml]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
commit = "8a776446f140e75e020ac3d46dc4488da7681931"

[grammars.cfhtml]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
commit = "8a776446f140e75e020ac3d46dc4488da7681931"

[grammars.cfscript]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
commit = "8a776446f140e75e020ac3d46dc4488da7681931"