id = "cfml"
name = "CFML"
description = "CFML support."
version = "0.1.1"
schema_version = 1
authors = ["Gareth Edwards <ghedwards@gmail.com>"]
repository = "https://github.com/cfmleditor/zed-cfml"

[grammars.cfhtml]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
commit = "a1314773958e48ff29d219507b8a6749be7265b7"
path = "./cfhtml"

[grammars.cfml]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
commit = "a1314773958e48ff29d219507b8a6749be7265b7"
path = "./cfml"

[grammars.cfscript]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
commit = "a1314773958e48ff29d219507b8a6749be7265b7"
path = "./cfscript"