id = "cfml"
name = "CFML"
description = "CFML support."
version = "0.2.11"
schema_version = 1
authors = ["Gareth Edwards <ghedwards@gmail.com>"]
repository = "https://github.com/cfmleditor/zed-cfml"

[language_servers.cfmleditor-lsp]
name = "cfmleditor-lsp"
languages = ["CFML (Tag)", "CFML (Script)", "CFML (Query)"]

[grammars.cfml]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
rev = "5d822c09c20a1b897fd29aded03d2dffdf281a3a"
path = "./cfml"

[grammars.cfscript]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
rev = "5d822c09c20a1b897fd29aded03d2dffdf281a3a"
path = "./cfscript"

[grammars.cfquery]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
rev = "5d822c09c20a1b897fd29aded03d2dffdf281a3a"
path = "./cfquery"