id = "cfml"
name = "CFML"
description = "CFML support."
version = "0.2.20"
schema_version = 1
authors = ["Gareth Edwards <ghedwards@gmail.com>"]
repository = "https://github.com/cfmleditor/zed-cfml"

[language_servers.cfmleditor-lsp]
name = "cfmleditor-lsp"
languages = ["CFML (Tag)", "CFML (Script)", "CFML (Query)"]

[grammars.cfml]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
rev = "e7e3d95c429daa31fc3137f47b7b7e690a4d5c4f"
path = "./cfml"

[grammars.cfscript]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
rev = "e7e3d95c429daa31fc3137f47b7b7e690a4d5c4f"
path = "./cfscript"

[grammars.cfquery]
repository = "https://github.com/cfmleditor/tree-sitter-cfml"
rev = "e7e3d95c429daa31fc3137f47b7b7e690a4d5c4f"
path = "./cfquery"
